### ISSUE TITLE
Depedancy Removal

### ISSUE THREAD

**Issue by xanth** [muiriswoulfe/NuGet-Transitive-Dependency-Finder#52]
## Summary
Thanks for your excellent tool, I needed something just like it but to automatically remove the transitive dependencies as well. I'd happily clean up what I have and submit a pull request if you're looking for contributions of this sort.

## Proposed Solution
Submit pull request adding a remove transitive dependencies mode & corresponding flag

**Comment by muiriswoulfe** [comment]
Glad you find the tool useful @xanth, and I'd be delighted to welcome your contribution.

Automated dependency removal is something I had been thinking about implementing. However, I uncovered a few issues that would make this more difficult to implement than I originally envisaged, and I decided to defer working on this until there was better testing in place (which you might have seen I've been working on recently).

A complete solution would probably need to consider:
- Removing a transitive dependency might result in the dependency being pulled from another dependency at a different version, e.g. if I remove the explicit use of package X v1.0 because package X is already referenced in package Y at v0.9, we will end up with a situation where package X gets downgraded to v0.9. The current mechanism for finding transitive dependencies is unfortunately currently unable to detect the possibility of this scenario.
- Not all dependencies are specified within .csproj files. For example, in this project, some of the dependencies are pulled in from .props files.

I'm not saying you need to think about all of this. If you have a solution that addresses some aspects of the problem, I think that would be very valuable in automating at least some of the cases (and thereby saving people manual effort, which is always great).
